version: "3.8"
services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: nbkpay
      POSTGRES_PASSWORD: nbkpay
      POSTGRES_DB: nbkpay
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
